apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090  # This should match the service name and port defined in your docker-compose.yml
    isDefault: true