name: Remote server setup

# targets (push)
on:
  workflow_dispatch:

# job info
jobs:
  # use github VM
  deploy-infrastructure:
    runs-on: ubuntu-latest
    
    # download code in to github VM 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # transport setup script to my VPS using SCP
      - name: Copy script via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "services/monitoring/**,scripts/**"
          target: "/root/vps-automation/"

      # setup SSH agent and deploy to remote server
      - name: Set up SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22  # My script will change port to 2222 but this is the default SSH port
          script: |
            echo "Successfully connected to remote VPS."
            # give execute permission to the setup script and run it
            chmod +x /root/vps-automation/scripts/setup.sh
            sudo /root/vps-automation/scripts/setup.sh
            # clean up the temporary script
            mv /root/vps-automation/scripts/setup.sh /root/vps-automation/scripts/DONTUSE
      
      - name: Wait for SSH Port 2222 to be ready
        run: |
          for i in {1..5}; do
            if nc -zv ${{ secrets.HOST }} 2222; then
              echo " SSH Port 2222 is OPEN!"
              exit 0
            fi
            echo " Port 2222 is still closed, retrying in 3s... ($i/5)"
            sleep 3
          done
          echo " Error: SSH Port 2222 timed out after 5 attempts."
          exit 1 # IF fail to connect 5 times, exit with error

      - name: Deploy Monitoring
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 2222  # My script will change port to 2222 
          # Here we pass the Secret to the SSH execution environment
          envs: CF_TUNNEL_TOKEN
          script: |
            cd /root/vps-automation
            # run the script
            bash ./scripts/deploy-monitoring.sh
        env:
          CF_TUNNEL_TOKEN: ${{ secrets.CF_TUNNEL_TOKEN }}