services:
  haproxy:
    image: haproxy:2.8-alpine3.23
    container_name: haproxy
    ports:
      - "80:80"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - monitor-net
    restart: always

  node-exporter:
    image: prom/node-exporter:v1.11.1
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      #exclude some mount points to avoid permission issues and irrelevant metrics
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - monitor-net

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.2
    container_name: cadvisor
    restart: unless-stopped
    privileged: true
    security_opt:
      - label:disable
    devices:
      - /dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /proc:/host/proc:ro
    command:
      - '--docker_only=false'
      - '--allow_dynamic_housekeeping=true'
      - '--housekeeping_interval=15s'
      - '--port=8080'
      - '--disable_metrics=cpu_topology,resctrl'
    ports:
      - "8080:8080"
    networks:
      - monitor-net

  prometheus:
    image: prom/prometheus:v3.11.2
    container_name: prometheus
    user: "65534:65534" # 確保權限正確
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ../../storage/prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - monitor-net
    restart: always

  grafana:
    image: grafana/grafana-oss:13.0.1 
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER} # From GitHub Secrets
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD} # From GitHub Secrets
    volumes:
    #Auto provisioning Grafana datasources and dashboards using bind mounts
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
    #static data storage for Grafana, readonly
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    #dynamic data storage for Grafana, read-write
      - ../../storage/grafana-data:/var/lib/grafana
    networks:
      - monitor-net
    restart: always

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --no-autoupdate run --token ${CF_TUNNEL_TOKEN} --protocol http2 # From GitHub Secrets
    networks:  
      - monitor-net
    restart: always

networks:
  monitor-net:
    driver: bridge